<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250407224919 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cidade (cid_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cid_nome VARCHAR(200) NOT NULL, cid_uf VARCHAR(2) NOT NULL, PRIMARY KEY(cid_id))');
        $this->addSql('CREATE TABLE endereco (end_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, end_tipo_logradouro VARCHAR(50) NOT NULL, end_logradouro VARCHAR(200) NOT NULL, end_numero INT NOT NULL, end_bairro VARCHAR(100) NOT NULL, cid_id INT DEFAULT NULL, PRIMARY KEY(end_id))');
        $this->addSql('CREATE INDEX IDX_F8E0D60E86C4B51D ON endereco (cid_id)');
        $this->addSql('CREATE TABLE foto_pessoa (fp_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fp_data DATE NOT NULL, fp_bucket VARCHAR(50) NOT NULL, fp_hash VARCHAR(50) NOT NULL, pes_id INT NOT NULL, PRIMARY KEY(fp_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2F0E01DBBB8470F ON foto_pessoa (pes_id)');
        $this->addSql('CREATE TABLE lotacao (lot_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lot_data_lotacao DATE NOT NULL, lot_data_remocao DATE DEFAULT NULL, lot_portaria VARCHAR(100) NOT NULL, pes_id INT NOT NULL, unid_id INT DEFAULT NULL, PRIMARY KEY(lot_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4C6AC15FBB8470F ON lotacao (pes_id)');
        $this->addSql('CREATE INDEX IDX_4C6AC15FA8A42792 ON lotacao (unid_id)');
        $this->addSql('CREATE TABLE pessoa (pes_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pes_nome VARCHAR(200) NOT NULL, pes_data_nascimento DATE NOT NULL, pes_sexo VARCHAR(9) NOT NULL, pes_mae VARCHAR(200) DEFAULT NULL, pes_pai VARCHAR(200) DEFAULT NULL, PRIMARY KEY(pes_id))');
        $this->addSql('CREATE TABLE pessoa_endereco (pes_id INT NOT NULL, end_id INT NOT NULL, PRIMARY KEY(pes_id, end_id))');
        $this->addSql('CREATE INDEX IDX_403BF131BB8470F ON pessoa_endereco (pes_id)');
        $this->addSql('CREATE INDEX IDX_403BF131E2BD8A10 ON pessoa_endereco (end_id)');
        $this->addSql('CREATE TABLE servidor_efetivo (se_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, se_matricula VARCHAR(20) NOT NULL, pes_id INT NOT NULL, PRIMARY KEY(se_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C379765B24B7EFF ON servidor_efetivo (se_matricula)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C379765BB8470F ON servidor_efetivo (pes_id)');
        $this->addSql('CREATE TABLE servidor_temporario (st_data_admissao DATE NOT NULL, st_data_demissao DATE DEFAULT NULL, pes_id INT NOT NULL, PRIMARY KEY(pes_id))');
        $this->addSql('CREATE TABLE unidade (unid_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, unid_nome VARCHAR(200) NOT NULL, unid_sigla VARCHAR(20) NOT NULL, PRIMARY KEY(unid_id))');
        $this->addSql('CREATE TABLE unidade_endereco (unid_id INT NOT NULL, end_id INT NOT NULL, PRIMARY KEY(unid_id, end_id))');
        $this->addSql('CREATE INDEX IDX_5E153544A8A42792 ON unidade_endereco (unid_id)');
        $this->addSql('CREATE INDEX IDX_5E153544E2BD8A10 ON unidade_endereco (end_id)');
        $this->addSql('ALTER TABLE endereco ADD CONSTRAINT FK_F8E0D60E86C4B51D FOREIGN KEY (cid_id) REFERENCES cidade (cid_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE foto_pessoa ADD CONSTRAINT FK_2F0E01DBBB8470F FOREIGN KEY (pes_id) REFERENCES pessoa (pes_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lotacao ADD CONSTRAINT FK_4C6AC15FBB8470F FOREIGN KEY (pes_id) REFERENCES pessoa (pes_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lotacao ADD CONSTRAINT FK_4C6AC15FA8A42792 FOREIGN KEY (unid_id) REFERENCES unidade (unid_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoa_endereco ADD CONSTRAINT FK_403BF131BB8470F FOREIGN KEY (pes_id) REFERENCES pessoa (pes_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoa_endereco ADD CONSTRAINT FK_403BF131E2BD8A10 FOREIGN KEY (end_id) REFERENCES endereco (end_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE servidor_efetivo ADD CONSTRAINT FK_C379765BB8470F FOREIGN KEY (pes_id) REFERENCES pessoa (pes_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE servidor_temporario ADD CONSTRAINT FK_1CEAA245BB8470F FOREIGN KEY (pes_id) REFERENCES pessoa (pes_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE unidade_endereco ADD CONSTRAINT FK_5E153544A8A42792 FOREIGN KEY (unid_id) REFERENCES unidade (unid_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE unidade_endereco ADD CONSTRAINT FK_5E153544E2BD8A10 FOREIGN KEY (end_id) REFERENCES endereco (end_id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE endereco DROP CONSTRAINT FK_F8E0D60E86C4B51D');
        $this->addSql('ALTER TABLE foto_pessoa DROP CONSTRAINT FK_2F0E01DBBB8470F');
        $this->addSql('ALTER TABLE lotacao DROP CONSTRAINT FK_4C6AC15FBB8470F');
        $this->addSql('ALTER TABLE lotacao DROP CONSTRAINT FK_4C6AC15FA8A42792');
        $this->addSql('ALTER TABLE pessoa_endereco DROP CONSTRAINT FK_403BF131BB8470F');
        $this->addSql('ALTER TABLE pessoa_endereco DROP CONSTRAINT FK_403BF131E2BD8A10');
        $this->addSql('ALTER TABLE servidor_efetivo DROP CONSTRAINT FK_C379765BB8470F');
        $this->addSql('ALTER TABLE servidor_temporario DROP CONSTRAINT FK_1CEAA245BB8470F');
        $this->addSql('ALTER TABLE unidade_endereco DROP CONSTRAINT FK_5E153544A8A42792');
        $this->addSql('ALTER TABLE unidade_endereco DROP CONSTRAINT FK_5E153544E2BD8A10');
        $this->addSql('DROP TABLE cidade');
        $this->addSql('DROP TABLE endereco');
        $this->addSql('DROP TABLE foto_pessoa');
        $this->addSql('DROP TABLE lotacao');
        $this->addSql('DROP TABLE pessoa');
        $this->addSql('DROP TABLE pessoa_endereco');
        $this->addSql('DROP TABLE servidor_efetivo');
        $this->addSql('DROP TABLE servidor_temporario');
        $this->addSql('DROP TABLE unidade');
        $this->addSql('DROP TABLE unidade_endereco');
    }
}
